servlet:
  session:
    store-type: none

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://dockerce01:3306/mysql
    username: root
    password: password
  
  security:
    user:
      name: john
      password: abcd1234 
      roles:
      - admin
  
k8s:
  secret-mount:
  - d:/Tools/apache-tomcat-9.0.20
  - d:/Tools/apache-tomcat-9.0.22

---
servlet:
  session:
    store-type: redis
  
spring:
  profiles: k8s
 
  datasource:
    url: jdbc:mysql://mysql-svc:3306/testdb
    #username: testuser    
    #password: passw0rd
    username: ${k8s-secret.mysql-secret.mysql-user}
    password: ${k8s-secret.mysql-secret.mysql-passwd}
  
  redis:
    host: redis-svc
    port: 6379
    #password: passw0rd
    password: ${k8s-secret.redis-secret.redis-passwd}

  security:
    user:
      name: ${k8s-secret.user-secret.login}
      password: ${k8s-secret.user-secret.passwd}
      roles:
      - admin
  
  #servlet:
  #  context-path: /app

k8s:
  secret-mount:
  - /usr/local/k8s/mysql-secret
  - /usr/local/k8s/redis-secret
  - /usr/local/k8s/user-secret
