---
spring:
  profiles: default
  
  datasource:
    url: jdbc:mysql://dockerce01:3306/mysql
    username: root
    password: password

---
servlet:
  session:
    store-type: redis
    
spring:
  profiles: k8s
  
  datasource:
    url: jdbc:mysql://mysql-svc:3306/testdb
    username: testuser
    password: passw0rd
  
  redis:
    host: redis-svc
    port: 6379
    password: passw0rd
    
k8s:
  secret-mount:
  - /run/secrets/mysql-secret
