apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  mysql-user: testuser
  mysql-passwd: passw0rd
---
apiVersion: v1
kind: Secret
metadata: 
  name: redis-secret
  labels:
    app: redis
type: Opaque
stringData:
  redis-passwd: passw0rd
---
apiVersion: v1
kind: Secret
metadata: 
  name: user-secret
  labels:
    app: springboot
type: Opaque
stringData:
  mysql-user: john
  mysql-passwd: abcd1234
