apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
    paths:
    - path: /app
      backend:
        serviceName: springboot-svc
        servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    pod-name: abc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      pod-name: abc
  template:
    metadata:
      name: springboot-pod
      labels:
        pod-name: abc
    spec:
      containers:
      - name: springboot-app
        image: kwonghung/spring-boot-k8s-secret:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s